"use client"
import { Provider } from "react-redux";
import "./css/style.css";

import { Inter } from "next/font/google";
import { store } from "@/redux/store";
import UserProvider from "@/components/UserProvider";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const dispatch=useAppDispatch()


  //   useEffect(() => {
  //     const token = localStorage.getItem('token');

  //     if (token) {
  //       dispatch(setAuthenticated(true)); // assumes a Redux action
  //     } else {
  //       dispatch(setAuthenticated(false));
  //     }

  //     dispatch(setInitialize(true)); // ✅ Mark auth check complete
  //   }, []);


  return (
    <Provider store={store}>
      <html lang="en" className="scroll-smooth">
        <body
          className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
        >
          <div className="flex  flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
            <UserProvider>
              {children}
            </UserProvider>
          </div>
        </body>
      </html>

    </Provider>
  );
}
